### ISSUE TITLE
FSP Checklist

### ISSUE THREAD

**Issue by Carly-Schaaf** [anthonykumasaka/KumaFlix#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
- You'll want to remove the Implementation Timeline page and add a Live Link (dummy for now)
- Also, the DB Schema link on the home page doesn't route to your schema

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - [x] Includes the following list for the 4 app specific MVPs:
    - [x] Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- You should do your production README on the last day (Friday the 21st), so you'll want to move it to the bottom of the list since things should be listed in the order in which they're done
- Also, in the title of the MVPs you'll want an estimate of how long you think each feature will take you
- Lastly, I assume your 'my list' feature will be your CRUD cycle, but you're going to want to detail what operations you plan (e.g. users can remove a movie from the list, users can add a movie, users can see their movies)
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- You will want to include the model-level associations in bullet-points underneath the tables (e.g. a list `belongs_to` a user, etc.)
- You should probably include a director column in the movies table, and possibly consider having an actors and castings table so that you can display the actors that are in the movie
- Also, I don't think you need both a lists table and a list_movies table. I might be wrong, but I think a user can only have one list, so your lists table would be the joins table connecting a `user_id` to a `movie_id`
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- State looks great!
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- I don't think you need a lists index route, since I assume you'll only ever be displaying the logged-in user's list
- Also, inside of your index method in `MoviesController`, you may want to be able to filter by genre, since I'm guessing you will often want to display all movies for a particular genre
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- You may want to make your frontend root route (`/`) just be the `movies` route, since I'm guessing that will be the homepage
- Also, I'm not sure you want a `/lists` route, which would mean you may want your `ListsShow` page to be nested under something like `/users/:id/list`

**Comment by Carly-Schaaf** [comment]
Looks like you're off to a great start, Anthony! I've left comments for each section above. Once you address the unchecked boxes, go ahead and get started, and let me know if you have any questions!

**Comment by anthonykumasaka** [comment]
Hey Carly I made some changes based off our meeting and your comments. My primary change was the DB. I removed my original joins table and added profiles. I now use the lists as a joins table between profiles and lists. I put in the notes that a profile has_one list. Let me know if there are more changes to be made. Thanks!

**Comment by Carly-Schaaf** [comment]
Looks good! A few more things, then you're set to go:
- [ ] Complete unchecked boxes for main wiki page (i.e. db schema link goes nowhere, does not contain a live dummy link to your app)
- [ ] Backend routes and frontend routes pages do not contain a profiles index route

**Comment by anthonykumasaka** [comment]
I think I made the right corrects. You may want to check my routes though. Thanks!

**Comment by Carly-Schaaf** [comment]
Looks good! You just need to add a patch route for a specific profile so that you can update it

**Comment by anthonykumasaka** [comment]
Cool I added it to my backend routes. Let me know if I need to change it.

**Comment by Carly-Schaaf** [comment]
Perfect! Feel free to get started on UserAuth
